#theme = "penumbra+"
#theme = "onedark"
theme = "base16_transparent"

[editor]
line-number = "absolute"
auto-completion = true
true-color = false
undercurl = false
cursorline = true
cursorcolumn = true
auto-info = true
color-modes = true
text-width = 99
bufferline = "multiple"
gutters = ["diagnostics", "spacer", "diff"]

[editor.statusline]
left = ["mode", "spinner", "separator", "file-name"]
center = ["separator", "version-control"]
#right = ["diagnostics", "separator", "file-type", "separator", "position"]
right = [
  "diagnostics",
  "separator",
  "selections",
  #"separator",
  #"position",
  #"position-percentage",
  #"spacer",
  "separator",
  "file-type",
]
#separator = "â„"
separator = "ğŸ”¥"
#separator = "Â¦"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false
ignore = false
git-ignore = false
git-global = false
git-exclude = false

[editor.indent-guides]
render = false
#character = "â•" # Some characters that work well: "â–", "â”†", "â”Š", "â¸½"
#skip-levels = 1

[keys.normal]
tab = "goto_next_buffer"
space = { x = ":buffer-close" }
C-w = { x = ":buffer-close" }
#[keys.normal.g]
#h = "goto_reference"
